//go:generate go run github.com/ethereum/go-ethereum/cmd/abigen --abi=WorkProofEscrow.abi --pkg=workproofescrow --type=WorkProofEscrow --out=autogen.go

// Package workproofescrow holds abigen-generated read bindings for
// contracts/WorkProofEscrow.sol, regenerated by
// scripts/generate-workproof-bindings.sh from the real forge build output
// (out/WorkProofEscrow.sol/WorkProofEscrow.json) -- never hand-written, so
// there is no risk of an ABI Argument definition silently drifting from the
// deployed contract the way a hand-rolled one could.
package workproofescrow
