//go:generate go run github.com/ethereum/go-ethereum/cmd/abigen --abi=WorkProofEscrow.abi --bin=WorkProofEscrow.bin --pkg=workproofescrow --type=WorkProofEscrow --out=autogen.go

// Package workproofescrow holds abigen-generated Deploy+Transact+Call
// bindings for contracts/WorkProofEscrow.sol, regenerated by
// scripts/generate-workproof-tools-bindings.sh from the real forge build
// output (out/WorkProofEscrow.sol/WorkProofEscrow.json) -- never
// hand-written. Distinct from go/pkg/contracts/workproofescrow, which is
// scoped to the extension's read-only verification needs and deliberately
// has no Deploy function; this package is scoped to the tools/ deployment
// pipeline and needs the full contract interface.
package workproofescrow
